### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by mcarans** [chrislit/abydos#286]
This is an impressive project unmatched by any other Python library currently available. Unfortunately, it seems like there have been no updates for a long time. Is the project no longer maintained?

**Comment by raffaelemancuso** [comment]
It doesn't work with Numpy > 2.0.

I'm getting:
```
Traceback (most recent call last):
  File "[ABRIDGED]/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-8a9c7b2de26d>", line 11, in <module>
    import abydos.distance as abd
  File "[ABRIDGED]/lib/python3.12/site-packages/abydos/distance/__init__.py", line 368, in <module>
    from ._aline import ALINE
  File "[ABRIDGED]/lib/python3.12/site-packages/abydos/distance/_aline.py", line 24, in <module>
    from numpy import NINF
ImportError: cannot import name 'NINF' from 'numpy' ([ABRIDGED]/lib/python3.12/site-packages/numpy/__init__.py)
```

When trying to import it

**Comment by brianrobt** [comment]
I'd say this project is no longer being maintained given that no updates have been made in 5 years.  That being said, it's always encouraged to fork works like this and maintain them yourself if you have the willingness and the time.

**Comment by denizberkin** [comment]
I commented on another issue about this @raffaem (https://github.com/chrislit/abydos/issues/287#issuecomment-2677762157).
You can also do this for NINF's (changing them with inf and changing all usages in the project with -np.inf) but I suggest cloning the most recent branch and changing `np.float_` occurrences to `np.float64`. If you do not want to bother, as I have mentioned in the comment again, you can pull my fork. It should work with numpy>2.0 and python>=3.10
